/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetCampaignCategoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCampaignCategoriesResponse{}

// GetCampaignCategoriesResponse Ответ на запрос списка категорий магазина.
type GetCampaignCategoriesResponse struct {
	// Список категорий.
	Categories []FeedCategoryDTO `json:"categories,omitempty"`
	Pager *FlippingPagerDTO `json:"pager,omitempty"`
}

// NewGetCampaignCategoriesResponse instantiates a new GetCampaignCategoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCampaignCategoriesResponse() *GetCampaignCategoriesResponse {
	this := GetCampaignCategoriesResponse{}
	return &this
}

// NewGetCampaignCategoriesResponseWithDefaults instantiates a new GetCampaignCategoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCampaignCategoriesResponseWithDefaults() *GetCampaignCategoriesResponse {
	this := GetCampaignCategoriesResponse{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *GetCampaignCategoriesResponse) GetCategories() []FeedCategoryDTO {
	if o == nil || IsNil(o.Categories) {
		var ret []FeedCategoryDTO
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCampaignCategoriesResponse) GetCategoriesOk() ([]FeedCategoryDTO, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *GetCampaignCategoriesResponse) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []FeedCategoryDTO and assigns it to the Categories field.
func (o *GetCampaignCategoriesResponse) SetCategories(v []FeedCategoryDTO) {
	o.Categories = v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *GetCampaignCategoriesResponse) GetPager() FlippingPagerDTO {
	if o == nil || IsNil(o.Pager) {
		var ret FlippingPagerDTO
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCampaignCategoriesResponse) GetPagerOk() (*FlippingPagerDTO, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *GetCampaignCategoriesResponse) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given FlippingPagerDTO and assigns it to the Pager field.
func (o *GetCampaignCategoriesResponse) SetPager(v FlippingPagerDTO) {
	o.Pager = &v
}

func (o GetCampaignCategoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCampaignCategoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	return toSerialize, nil
}

type NullableGetCampaignCategoriesResponse struct {
	value *GetCampaignCategoriesResponse
	isSet bool
}

func (v NullableGetCampaignCategoriesResponse) Get() *GetCampaignCategoriesResponse {
	return v.value
}

func (v *NullableGetCampaignCategoriesResponse) Set(val *GetCampaignCategoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCampaignCategoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCampaignCategoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCampaignCategoriesResponse(val *GetCampaignCategoriesResponse) *NullableGetCampaignCategoriesResponse {
	return &NullableGetCampaignCategoriesResponse{value: val, isSet: true}
}

func (v NullableGetCampaignCategoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCampaignCategoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


