/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ya-client

import (
	"encoding/json"
)

// checks if the OfferMappingSuggestionsListDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferMappingSuggestionsListDTO{}

// OfferMappingSuggestionsListDTO Список рекомендованных карточек товара.
type OfferMappingSuggestionsListDTO struct {
	// Список товаров.
	Offers []EnrichedMappingsOfferDTO `json:"offers,omitempty"`
}

// NewOfferMappingSuggestionsListDTO instantiates a new OfferMappingSuggestionsListDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferMappingSuggestionsListDTO() *OfferMappingSuggestionsListDTO {
	this := OfferMappingSuggestionsListDTO{}
	return &this
}

// NewOfferMappingSuggestionsListDTOWithDefaults instantiates a new OfferMappingSuggestionsListDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferMappingSuggestionsListDTOWithDefaults() *OfferMappingSuggestionsListDTO {
	this := OfferMappingSuggestionsListDTO{}
	return &this
}

// GetOffers returns the Offers field value if set, zero value otherwise.
func (o *OfferMappingSuggestionsListDTO) GetOffers() []EnrichedMappingsOfferDTO {
	if o == nil || IsNil(o.Offers) {
		var ret []EnrichedMappingsOfferDTO
		return ret
	}
	return o.Offers
}

// GetOffersOk returns a tuple with the Offers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferMappingSuggestionsListDTO) GetOffersOk() ([]EnrichedMappingsOfferDTO, bool) {
	if o == nil || IsNil(o.Offers) {
		return nil, false
	}
	return o.Offers, true
}

// HasOffers returns a boolean if a field has been set.
func (o *OfferMappingSuggestionsListDTO) HasOffers() bool {
	if o != nil && !IsNil(o.Offers) {
		return true
	}

	return false
}

// SetOffers gets a reference to the given []EnrichedMappingsOfferDTO and assigns it to the Offers field.
func (o *OfferMappingSuggestionsListDTO) SetOffers(v []EnrichedMappingsOfferDTO) {
	o.Offers = v
}

func (o OfferMappingSuggestionsListDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferMappingSuggestionsListDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offers) {
		toSerialize["offers"] = o.Offers
	}
	return toSerialize, nil
}

type NullableOfferMappingSuggestionsListDTO struct {
	value *OfferMappingSuggestionsListDTO
	isSet bool
}

func (v NullableOfferMappingSuggestionsListDTO) Get() *OfferMappingSuggestionsListDTO {
	return v.value
}

func (v *NullableOfferMappingSuggestionsListDTO) Set(val *OfferMappingSuggestionsListDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferMappingSuggestionsListDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferMappingSuggestionsListDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferMappingSuggestionsListDTO(val *OfferMappingSuggestionsListDTO) *NullableOfferMappingSuggestionsListDTO {
	return &NullableOfferMappingSuggestionsListDTO{value: val, isSet: true}
}

func (v NullableOfferMappingSuggestionsListDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferMappingSuggestionsListDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


