/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ya-client

import (
	"encoding/json"
)

// checks if the FeedIndexLogsErrorDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeedIndexLogsErrorDTO{}

// FeedIndexLogsErrorDTO Информация об ошибке, произошедшей во время индексации прайс-листа.  Выводится, если во время индексации произошли ошибки (`index-log-record status=ERROR`). 
type FeedIndexLogsErrorDTO struct {
	// HTTP-код ошибки индексации прайс-листа.  Выводится, если `type=DOWNLOAD_HTTP_ERROR`. 
	HttpStatusCode *int32 `json:"httpStatusCode,omitempty"`
	Type *FeedIndexLogsErrorType `json:"type,omitempty"`
	// Описание ошибки.  Выводится, если `type=DOWNLOAD_ERROR`. 
	Description *string `json:"description,omitempty"`
}

// NewFeedIndexLogsErrorDTO instantiates a new FeedIndexLogsErrorDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeedIndexLogsErrorDTO() *FeedIndexLogsErrorDTO {
	this := FeedIndexLogsErrorDTO{}
	return &this
}

// NewFeedIndexLogsErrorDTOWithDefaults instantiates a new FeedIndexLogsErrorDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeedIndexLogsErrorDTOWithDefaults() *FeedIndexLogsErrorDTO {
	this := FeedIndexLogsErrorDTO{}
	return &this
}

// GetHttpStatusCode returns the HttpStatusCode field value if set, zero value otherwise.
func (o *FeedIndexLogsErrorDTO) GetHttpStatusCode() int32 {
	if o == nil || IsNil(o.HttpStatusCode) {
		var ret int32
		return ret
	}
	return *o.HttpStatusCode
}

// GetHttpStatusCodeOk returns a tuple with the HttpStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedIndexLogsErrorDTO) GetHttpStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpStatusCode) {
		return nil, false
	}
	return o.HttpStatusCode, true
}

// HasHttpStatusCode returns a boolean if a field has been set.
func (o *FeedIndexLogsErrorDTO) HasHttpStatusCode() bool {
	if o != nil && !IsNil(o.HttpStatusCode) {
		return true
	}

	return false
}

// SetHttpStatusCode gets a reference to the given int32 and assigns it to the HttpStatusCode field.
func (o *FeedIndexLogsErrorDTO) SetHttpStatusCode(v int32) {
	o.HttpStatusCode = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FeedIndexLogsErrorDTO) GetType() FeedIndexLogsErrorType {
	if o == nil || IsNil(o.Type) {
		var ret FeedIndexLogsErrorType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedIndexLogsErrorDTO) GetTypeOk() (*FeedIndexLogsErrorType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FeedIndexLogsErrorDTO) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given FeedIndexLogsErrorType and assigns it to the Type field.
func (o *FeedIndexLogsErrorDTO) SetType(v FeedIndexLogsErrorType) {
	o.Type = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FeedIndexLogsErrorDTO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedIndexLogsErrorDTO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FeedIndexLogsErrorDTO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FeedIndexLogsErrorDTO) SetDescription(v string) {
	o.Description = &v
}

func (o FeedIndexLogsErrorDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeedIndexLogsErrorDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HttpStatusCode) {
		toSerialize["httpStatusCode"] = o.HttpStatusCode
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableFeedIndexLogsErrorDTO struct {
	value *FeedIndexLogsErrorDTO
	isSet bool
}

func (v NullableFeedIndexLogsErrorDTO) Get() *FeedIndexLogsErrorDTO {
	return v.value
}

func (v *NullableFeedIndexLogsErrorDTO) Set(val *FeedIndexLogsErrorDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeedIndexLogsErrorDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeedIndexLogsErrorDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeedIndexLogsErrorDTO(val *FeedIndexLogsErrorDTO) *NullableFeedIndexLogsErrorDTO {
	return &NullableFeedIndexLogsErrorDTO{value: val, isSet: true}
}

func (v NullableFeedIndexLogsErrorDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeedIndexLogsErrorDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


