/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrdersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrdersResponse{}

// GetOrdersResponse Модель для ответа API списка информации по заказам.
type GetOrdersResponse struct {
	Pager *FlippingPagerDTO `json:"pager,omitempty"`
	// Модель заказа. 
	Orders []OrderDTO `json:"orders,omitempty"`
}

// NewGetOrdersResponse instantiates a new GetOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrdersResponse() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// NewGetOrdersResponseWithDefaults instantiates a new GetOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrdersResponseWithDefaults() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *GetOrdersResponse) GetPager() FlippingPagerDTO {
	if o == nil || IsNil(o.Pager) {
		var ret FlippingPagerDTO
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersResponse) GetPagerOk() (*FlippingPagerDTO, bool) {
	if o == nil || IsNil(o.Pager) {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *GetOrdersResponse) HasPager() bool {
	if o != nil && !IsNil(o.Pager) {
		return true
	}

	return false
}

// SetPager gets a reference to the given FlippingPagerDTO and assigns it to the Pager field.
func (o *GetOrdersResponse) SetPager(v FlippingPagerDTO) {
	o.Pager = &v
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *GetOrdersResponse) GetOrders() []OrderDTO {
	if o == nil || IsNil(o.Orders) {
		var ret []OrderDTO
		return ret
	}
	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersResponse) GetOrdersOk() ([]OrderDTO, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *GetOrdersResponse) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []OrderDTO and assigns it to the Orders field.
func (o *GetOrdersResponse) SetOrders(v []OrderDTO) {
	o.Orders = v
}

func (o GetOrdersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrdersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pager) {
		toSerialize["pager"] = o.Pager
	}
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	return toSerialize, nil
}

type NullableGetOrdersResponse struct {
	value *GetOrdersResponse
	isSet bool
}

func (v NullableGetOrdersResponse) Get() *GetOrdersResponse {
	return v.value
}

func (v *NullableGetOrdersResponse) Set(val *GetOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrdersResponse(val *GetOrdersResponse) *NullableGetOrdersResponse {
	return &NullableGetOrdersResponse{value: val, isSet: true}
}

func (v NullableGetOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


