description: >
  Источник информации о расписании работы службы доставки.

  Возможные значения:

  * `WEB` — информация получена из настроек личного кабинета магазина на Яндекс
  Маркете.

  * `YML` — информация получена из прайс-листа магазина.
type: string
enum:
  - WEB
  - YML
