description: >-
  Период, за который рассчитывается итоговый список нерабочих дней службы
  доставки.
type: object
properties:
  fromDate:
    description: >
      Дата (включительно) начала периода, по которому рассчитан итоговый список
      нерабочих дней службы доставки.


      Формат даты: `ДД-ММ-ГГГГ`.
    $ref: ./DateDdMmYyyy.yaml
  toDate:
    description: >
      Дата (включительно) окончания периода, по которому рассчитан итоговый
      список нерабочих дней службы доставки.


      Формат даты: `ДД-ММ-ГГГГ`.
    $ref: ./DateDdMmYyyy.yaml
